
function isInt(vl){
    if(typeof vl=="number"){
        vl = Number(vl);
        if (vl%1 ==0){
            return true;
        }else{
            return false;
        }
    }else{  
        return false;
    }

}



function raiz(v){
    //decompor raiz
/*
Ex; raiz(24)
  resultado  2√2*3 = 2√6

 */
    var i = 0;
    
    while (i<20){
        //100
        //
        if(){
            
        }

        i++;

    }

}